### ISSUE TITLE
In the About us section , the cover picture should be "width: 581.32px;" "height: 392.39px;" ( 744px , 744px+)

### ISSUE THREAD

**Issue by Haykaztkd** [hrachocode/hydralab#155]
Figma

![Image](https://user-images.githubusercontent.com/120453816/212045609-f5088352-79ee-41c8-8465-93629fed2189.PNG)

**Comment by tumero58** [comment]
proportions are dynamic

**Comment by tumero58** [comment]
proportions are dynamic
