### ISSUE TITLE
On the homepage has the width of the upper and inner segment, which does not correspond to Figma

### ISSUE THREAD

**Issue by Haykaztkd** [hrachocode/hydralab#162]
![Image](https://user-images.githubusercontent.com/120453816/212311955-6265919a-0fd3-42d8-93e0-6116c4c348ba.PNG)

**Comment by Haykaztkd** [comment]
![Image](https://user-images.githubusercontent.com/120453816/212312009-0d0ff576-f008-4038-aa08-1f7272030932.PNG)

**Comment by tumero58** [comment]
background image size is the reason, cannot change that as of yet.
